### PR TITLE
BREAKING CHANGE(potentially): Stop periodic rotation of credentials

### PR DESCRIPTION
**Pull request by x10an14**
Ref: https://github.com/navikt/pig/blob/master/aiven/ref/2021-04-20-credentials.md

### CODE REVIEW

**Comment by ambientsound** [comment]
Looks ok so far. The second part will be to not rotate credentials for existing service users when topic is synchronized.

**Review by mortenlj — COMMENTED** [review]
:+1: 

Probably should change `Topic.NeedsSynchronization` in https://github.com/nais/liberator/blob/2180d82616c3f7356bc85e8fd4a99ee262390df5/pkg/apis/kafka.nais.io/v1/kafkarator_types.go#L151 too?

**Comment by x10an14** [comment]
> Looks ok so far. The second part will be to not rotate credentials for existing service users when topic is synchronized.
@ambientsound Yup! We've split that up (me and @mortenlj). This PR is just for the "automatic" rotation triggered by expiry time.

**Comment by x10an14** [comment]
> Probably should change Topic.NeedsSynchronization in https://github.com/nais/liberator/blob/2180d82616c3f7356bc85e8fd4a99ee262390df5/pkg/apis/kafka.nais.io/v1/kafkarator_types.go#L151 too?

Don't disagree! Wilco. Merging this one tomorrow if no other/new comments/suggestions have been added.

**Comment by mortenlj** [comment]
Just a side-question: In what way would this be a "breaking change"?

**Comment by x10an14** [comment]
> @mortenlj: Just a side-question: In what way would this be a "breaking change"?

I have no idea if anything is relying on this rotation that's controlled by a time-limited period.
That's all.

**Review by mortenlj — APPROVED** [review]

**Comment by mortenlj** [comment]
> > Probably should change Topic.NeedsSynchronization in https://github.com/nais/liberator/blob/2180d82616c3f7356bc85e8fd4a99ee262390df5/pkg/apis/kafka.nais.io/v1/kafkarator_types.go#L151 too?
> 
> Don't disagree! Wilco. Merging this one tomorrow if no other/new comments/suggestions have been added.

My bad. You made the changes there, but never updated the reference to liberator in this PR. When a topic was updated, it no longer had the `.Status.CredentialsExpiryTime` field, but since it was still using the old version of liberator, missing field means create new credentials. Cue looping while processing topic, spawning new credentials on every loop.

I've pushed a fix to use latest version of liberator, hopefully that should solve the problem before anyone else updates their topics.

**Pull request merged**
