### PR TITLE
Add FullName of topic to status

### PR DESCRIPTION
**Pull request by mortenlj**

### CODE REVIEW

**Review by ambientsound — COMMENTED** [review]
Not sure about the naming of this field; is it self explanatory?

**Comment by mortenlj** [comment]
> Not sure about the naming of this field; is it self explanatory?

I considered `FinalName`, but didn't really think that was any better. Suggestions?

**Comment by ambientsound** [comment]
Maybe `CanonicalName`?

**Comment by ambientsound** [comment]
`FullyQualifiedName`?

**Comment by mortenlj** [comment]
Not sure I think either of those are any better to be honest. `FullyQualifiedName` might be a tad better, but not sure it would make a difference.

**Comment by ambientsound** [comment]
Name contest in Slack?

**Comment by mortenlj** [comment]
> Name contest in Slack?

Good idea. Will follow up with results this evening.

**Comment by mortenlj** [comment]
`FullyQualifiedName` seems to be the winner.

**Review by ambientsound — APPROVED** [review]

**Pull request merged**
